const fs = require('fs');
const path = require('path');
fs.mkdirSync(path.join(__dirname, 'src/components'), {recursive: true});
fs.mkdirSync(path.join(__dirname, 'src/pages/public'), {recursive: true});
fs.mkdirSync(path.join(__dirname, 'src/pages/admin'), {recursive: true});
fs.mkdirSync(path.join(__dirname, 'src/pages/branch'), {recursive: true});
fs.mkdirSync(path.join(__dirname, 'src/pages/staff'), {recursive: true});
fs.mkdirSync(path.join(__dirname, 'src/pages/member'), {recursive: true});
fs.mkdirSync(path.join(__dirname, 'src/hooks'), {recursive: true});
fs.mkdirSync(path.join(__dirname, 'src/services'), {recursive: true});
fs.mkdirSync(path.join(__dirname, 'src/context'), {recursive: true});
fs.mkdirSync(path.join(__dirname, 'src/utils'), {recursive: true});
console.log('✓ Directories created');
